name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  actions: write
  attestations: write
  id-token: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-24.04
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
          fetch-tags: true
          fetch-depth: 0

      - name: build essential
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: stable

      - uses: bufbuild/buf-action@8f4a1456a0ab6a1eb80ba68e53832e6fcfacc16c # v1.3.0

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...

      - name: "Cut release if 'Release-status: cut' in commit message"
        if: "${{ github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, 'Release-status: cut') }}"
        uses: benc-uk/workflow-dispatch@e2e5e9a103e331dad343f381a29e654aea3cf8fc # v1.2.4
        with:
          workflow: "release.yaml"
